### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by crazyjat** [Xpazeman/tld-better-bases#17]
[20:10:58.327] Support Module Loaded: B:\Games\Steam\steamapps\common\TheLongDark\MelonLoader\Dependencies\SupportModules\Il2Cpp.dll
[20:10:58.331] Failed to load all types in assembly BetterBases, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null due to: Unable to load one or more of the requested types.
Could not load file or assembly 'ModSettings, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'ModSettings, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at MelonLoader.MelonUtils.GetValidTypes(Assembly asm, LemonFunc`2 predicate) in D:\a\MelonLoader\MelonLoader\MelonLoader\MelonUtils.cs:line 257
System.IO.FileNotFoundException: Could not load file or assembly 'ModSettings, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'ModSettings, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'
[20:10:58.332] Registered mono type BetterBases.ChangeLayer in il2cpp domain
[20:10:58.333] Registered mono type BetterBases.MoveableObject in il2cpp domain
[20:10:58.333] Registered mono type BetterBases.RepairableContainer in il2cpp domain
[20:10:58.784] [BetterBases] System.IO.FileNotFoundException: Could not load file or assembly 'ModData, Version=1.5.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'ModData, Version=1.5.1.0, Culture=neutral, PublicKeyToken=null'
   at BetterBases.BetterBases.OnInitializeMelon()
   at MelonLoader.MelonBase.LoaderInitialized() in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\MelonBase.cs:line 440Setting breakpad minidump AppID = 305620
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198014041394 [API loaded no]

**Comment by crazyjat** [comment]
NO WHERE DOES IT SAY THIS MOD NEEDS THE MOD DATA MOD TOO. Some helpful information you just don't provide. Thanks for that.

**Comment by crazyjat** [comment]
OR MOD SETTINGS. JFC

**Comment by Xpazeman** [comment]
All the info it's on the modlist. Learn to read.
